server:
  port: 80

spring:
  datasource:
     url: jdbc:mysql://127.0.0.1/c83-s2-ply-damai?serverTimezone=UTC&CharacterEncoding=UTF-8&useSSL=false
     username: root
     password: a
     driver-class-name: com.mysql.jdbc.Driver

# 邮件发送  Yml 配置规则: 如果某个阶段有重复配置情况, 必要要合并
  mail:
      # 邮箱服务器地址
      host: smtp.qq.com
      # 用户名
      username: 1062474071@qq.com
      # 密码 
      password: gyohgqqacmaabegc
      default-encoding: UTF-8

# 日志配置
logging:
  level:
    com:
      yc:
        C83S3PlySpringBoot:
          dao: debug
          web: warn


# 以谁来发送邮件  ==> 用户自定义的属性
mail:
   fromMail:
      addr: 1062474071@qq.com